### ISSUE TITLE
string encoding NoMethod error

### ISSUE THREAD

**Issue by dvogtfstr** [vcr/vcr#1042]
I have a 500 cassette and getting this error:

```
NoMethodError: undefined method `encoding' for nil:NilClass

            return string if encoding.nil? || string.encoding.name == encoding
                                                    ^^^^^^^^^
from .../ruby/3.1.6/lib/ruby/gems/3.1.0/gems/vcr-6.2.0/lib/vcr/structs.rb:35:in `try_encode_string'
```

Cassette:
```
---
http_interactions:
- request:
    method: post
    uri: ...
    body:
      encoding: UTF-8
    headers:
      Accept:
      - text/xml
      Content-Type:
      - application/soap+xml;charset=UTF-8
      User-Agent:
      - ...
      Soapaction:
      - '"put"'
      Content-Length:
      - '2638'
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 500
      message: ''
    headers:
      Date:
      - Tue, 19 Nov 2024 10:14:20 GMT
      Server:
      - Apache
      Content-Type:
      - text/xml;charset=utf-8
      P3p:
      - CP="NOI DSP COR NID CUR ADM DEV OUR BUS"
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Methods:
      - POST, GET, OPTIONS, PUT, DELETE
      Connection:
      - close
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
  recorded_at: Tue, 19 Nov 2024 10:14:20 GMT
recorded_with: VCR 6.2.0
```

Ruby 3.1.6
Gem 6.2.0
HTTP     faraday (2.12.1)
      faraday-net_http (>= 2.0, < 3.5)
Rails     rails (7.2.2.1)
Rspec     rspec (3.13.0)

Have anyone an idea? 🙏🏾

**Comment by andrehjr** [comment]
Hi,

How did you generate this cassette? Can you try generating it again?

The body entries should have something like the following:

https://github.com/vcr/vcr/blob/master/features/cassettes/allow_unused_http_interactions.feature#L29-L31

```yaml
          body: 
            encoding: UTF-8
            string: ""

```

Can you try adding the `string: ""` to see if it works?
