### ISSUE TITLE
Problem using VCR and Instagram gem

### ISSUE THREAD

**Issue by jam1401** [vcr/vcr#159]
I'm using the Instagram GEM in my application when I use VCR in my tests I run into problems and I have no idea how to solve the issue. I cant figure out if this is a VCR issue or not. Basically the initial request fills a cassette with the following data

```
http_interactions:
- request:
    method: get
    uri: https://api.instagram.com/v1/users/self/feed.json?access_token=xxxxxxxxx
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json; charset=utf-8
      User-Agent:
      - Instagram Ruby Gem 0.8.3
      Authorization:
      - Token token=xxxxxxx
  response:
    status:
      code: 200
      message: !!null 
    headers:
      content-language:
      - en
      content-type:
      - application/json; charset=utf-8
      date:
      - Tue, 01 May 2012 03:03:39 GMT
      server:
      - nginx/0.8.54
      vary:
      - Accept-Language, Cookie
      x-ratelimit-limit:
      - '5000'
      x-ratelimit-remaining:
      - '4995'
      content-length:
      - '2036'
      connection:
      - keep-alive
    body:
      encoding: US-ASCII
      string: ! '#<Hashie::Mash data=[#<Hashie::Mash attribution=nil caption=nil comments=#<Hashie::Mash
        count=0 data=[]> created_time="1335764579" filter="Normal" id="xxxxxxxxxxxxxx"
        images=#<Hashie::Mash low_resolution=#<Hashie::Mash height=306 url="http://distilleryimage4.instagram.com/5845149c928711e19e4a12313813ffc0_6.jpg"
        width=306> standard_resolution=#<Hashie::Mash height=612 url="http://distilleryimage4.instagram.com/5845149c928711e19e4a12313813ffc0_7.jpg"
        width=612> thumbnail=#<Hashie::Mash height=150 url="http://distilleryimage4.instagram.com/5845149c928711e19e4a12313813ffc0_5.jpg"
        width=150>> likes=#<Hashie::Mash count=1 data=[#<Hashie::Mash full_name="Rich
        .... >
```

And the tests pass without a problem. However subsequent requests that pull from the Cassette fail 

NoMethodError: undefined method `each' for #String:0x007f9676681758

It seems that VCR is simply returning a string and the API just delivers it to the app and things fail

Any suggestions? been stuck on this for a while and cant seem to find a solution.

thanks

Jeff
