### ISSUE TITLE
basic_auth token being recorded in the URL, not headers

### ISSUE THREAD

**Issue by c10l** [vcr/vcr#189]
When I make a call that uses basic_auth for authentication, VCR records the credentials in the URL of the request, such as "http://user:pass@some-url/", even though it has been sent in the request headers.

This behavior breaks webmock's verifications based on base_uri, since those don't include the auth token in the URL.

Find below snippets of the cassette and the webmock match failure.

``` yaml

---
http_interactions:
- request:
    method: post
    uri: http://username:password@server/v1/channels/
    body:
      encoding: UTF-8
      string: ! '{"external_id":"8a39ad334c74297a4e56b0ff517aa6397ba839e9","name":"05c769c33705db725bf61f257ffc698ca7ddf25a","description":"97237da7f2784d38eb1651c8760886df40130d80"}'
```

``` bash
     Failure/Error: a_request(:post, "#{@base_uri}/").with(auth:   @auth,
       The request POST http://server/v1/channels/ with body "{\"external_id\":\"6e858a531947c1ffef37ad592edc10db1973e979\",\"name\":\"66e42faaa6267e0b9c585247f8962661d62f6ea6\",\"description\":\"4d3d2bb153e853db315cd5f226f1c1e88bd2c577\"}" was expected to execute 1 time but it executed 0 times

       The following requests were made:

       POST http://username:password@server/v1/channels/ with body '{"external_id":"6e858a531947c1ffef37ad592edc10db1973e979","name":"66e42faaa6267e0b9c585247f8962661d62f6ea6","description":"4d3d2bb153e853db315cd5f226f1c1e88bd2c577"}' with headers {'Accept'=>'application/json', 'Content-Type'=>'application/json'} was made 2 times
```
