### ISSUE TITLE
failure with recording S3 uploads through carrierwave

### ISSUE THREAD

**Issue by nclark** [vcr/vcr#198]
this issue is a follow up to the email thread [here](https://groups.google.com/forum/#!topic/vcr-ruby/BYXKg69T17g).

demo repository [here](https://github.com/nclark/webmock-demo).

it works when "hooking into" webmock & excon, but not when "hooking into" webmock by itself. you can see the difference by reverting the last commit. you will need a `config/settings.yml` with:

``` yaml
test:
  aws_access_key_id: [your aws access key id]
  aws_secret_access_key: [your aws secret access key]
  asset_bucket: [your test bucket]
```

i'm not sure where the issue is, vcr, webmock, or elsewhere. but changing

``` ruby
  VCR.configure do |c|
    # ...
    c.hook_into :webmock
  end
```

to 

``` ruby
  VCR.configure do |c|
    #...
    c.hook_into :excon, :webmock
  end

```

gets the test passing.
