### ISSUE TITLE
cassette files still contains username password!

### ISSUE THREAD

**Issue by goodwill** [vcr/vcr#205]
After I did my recording, I realise the sensitive http_basic_auth is still everywhere:

``` yaml
request:
    method: post
    uri: https://<USERNAME>:<PASSWORD>@somehwere.com/accounts/create
    body:
      encoding: US-ASCII
      string: ! ' '
    headers:
      Accept:
      - ! '*/*; q=0.5, application/xml'
      Accept-Encoding:
      - gzip, deflate
      Content-Length:
      - '1'
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Origin:
      - ! '*'
      Content-Type:
      - application/json
      Date:
      - Wed, 31 Oct 2012 07:56:13 GMT
      Server:
      - journey/0.4.0
      Content-Length:
      - '291'
      Connection:
      - keep-alive
    body:
      encoding: US-ASCII
      string: !ruby/string
        str: ! "{..."
        net_http_res: &70176758670660 !ruby/object:Net::HTTPOK
          http_version: '1.0'
          code: '200'
          message: OK
          header:
            access-control-allow-origin:
            - ! '*'
            content-type:
            - application/json
            date:
            - Wed, 31 Oct 2012 07:56:13 GMT
            server:
            - journey/0.4.0
            content-length:
            - '291'
            connection:
            - keep-alive
          body: !ruby/string
            str: ! "{...}"
            net_http_res: *70176758670660
            args: &70176727350020
              :timeout: 9
              :open_timeout: 7
              :user: MY_REAL_USERNAME
              :password: MY_REAL_PASSWORD
              :verify_ssl: false
              :method: :post
              :url: https://host/accounts/create
              :payload: ! ' '
              :headers: {}
            code: 200
          read: true
          __read_body_previously_called: true
        args: *70176727350020
        code: 200
    http_version: 
  recorded_at: Wed, 31 Oct 2012 07:56:14 GMT
```

Notice the code inside args with :user: and :password: still contains my http basic auth, only the uri has been filtered.
