### ISSUE TITLE
YAML serialization does not work on Ruby 2.0

### ISSUE THREAD

**Issue by morgoth** [vcr/vcr#210]
Hi.

When using ruby-2.0.0-preview1, YAML cassette seriazliation does not work.
Output from yaml file:

``` yaml

---
http_interactions:
- :request: 
  :response: 
  :recorded_at: 
recorded_with: VCR 2.3.0

```

Looks like JSON serialization is working fine
