### ISSUE TITLE
VCR 2.3.0 not recording URL Parameters from Typhoeus 0.5.3

### ISSUE THREAD

**Issue by bkimble** [vcr/vcr#235]
It appears that VCR 2.3.0 is not properly storing URL parameters when recording cassettes made with Typhoeus 0.5.3:

```
require 'rubygems'
require 'vcr'
require 'typhoeus'

VCR.configure do |c|
  c.cassette_library_dir = '.'
  c.hook_into :typhoeus
end

VCR.use_cassette("test", :record => :new_episodes) do  
  hydra = Typhoeus::Hydra.new
  req = Typhoeus::Request.new("http://www.yelp.com/search", :params => {:find_desc=>'kittens', :find_loc=>'San+Francisco%2C+CA'}, :followlocation => true)
  hydra.queue(req)
  hydra.run  
end
```

creates the cassete:

```
--- 
recorded_with: VCR 2.3.0
http_interactions: 
- request: 
    method: get
    uri: http://www.yelp.com/search
    body: 
      string: ""
    headers: 
      User-Agent: 
      - Typhoeus - https://github.com/typhoeus/typhoeus
  response: 
    status: 
      code: 200
      message: OK
    headers: 
      Vary: 
      - Accept-Encoding,User-Agent
      Date: 
      - Wed, 12 Dec 2012 20:59:50 GMT
      X-Node: 
      - wsgi, web36, www_all
      Content-Type: 
      - text/html; charset=UTF-8
      Content-Length: 
      - "105870"
      X-Mode: 
      - ro
      X-Proxied: 
      - lb1
      Server: 
      - Apache
      Set-Cookie: 
      - yuv=zCvyWkMspEVW_I6OsvoRPN7Ft_-fGiBwc0Q0XDkSpYkGDaPJT-pTxlpEtl5O_cuI1iwzqmFb_brTsNJJhIa9hqDfc47EHosR; Domain=.yelp.com; Max-Age=630720000; Path=/; expires=Tue, 07-Dec-2032 20:59:50 GMT
      - bse=a2c4d5137e7499a03647460c8132d154; Domain=.yelp.com; Path=/; HttpOnly
      - hl=en_US; Domain=.yelp.com; Max-Age=630720000; Path=/; expires=Tue, 07-Dec-2032 20:59:50 GMT
      - recentlocations=Financial+District%2C+San+Francisco%2C+CA%2C+USA; Domain=.yelp.com; Path=/
      - location=%7B%22unformatted%22%3A+%22Inner+Richmond%2C+San+Francisco%2C+CA%22%2C+%22city%22%3A+%22San+Francisco%22%2C+%22state%22%3A+%22CA%22%2C+%22country%22%3A+%22US%22%7D; Domain=.yelp.com; Max-Age=630720000; Path=/; expires=Tue, 07-Dec-2032 20:59:50 GMT
      Cache-Control: 
      - private
      Connection: 
      - close
    body: (snipped)
    http_version: "1.1"
  recorded_at: Wed, 12 Dec 2012 20:59:57 GMT
```

This appears to be because VCR uses Typhoeus::Request#url to store the URL. In versions before 0.5, this contained the parameters - but no longer.

```
# typhoeus 0.4.2
Typhoeus::Request.new("http://www.yahoo.com",:params => {:foo => 'bar'}).url
 => "http://www.yahoo.com?foo=bar"

 # typhoeus 0.5.3
 Typhoeus::Request.new("http://www.yahoo.com",:params => {:foo => 'bar'}).url
  => "http://www.yahoo.com" 
```

Is this a known issue with a solution to get around it? Thanks in advance!
