### ISSUE TITLE
VCR doesn't keep headers in the response

### ISSUE THREAD

**Issue by ciniglio** [vcr/vcr#299]
When recording a request, VCR keeps the response headers:

```
http_interactions:
- request:
    method: get
    uri: https://graph.facebook.com/#{page_id}/posts?access_token=#{token}&limit=500
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.8.7
      If-None-Match:
      - ''
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Origin:
      - ! '*'
      Cache-Control:
      - private, no-cache, no-store, must-revalidate
      Content-Type:
      - application/json; charset=UTF-8
      Etag:
      - ! '"d87fd3af419ed2570db869919866b4a576e67fc4"'
      Expires:
      - Sat, 01 Jan 2000 00:00:00 GMT
      Pragma:
      - no-cache
      Date:
      - Wed, 29 May 2013 21:42:44 GMT
      Connection:
      - keep-alive
      Content-Length:
      - '9'
    body:
      encoding: US-ASCII
      string: ! '{"data":[]}'
```

configuration:

```
VCR.configure do |c|
  c.cassette_library_dir = 'vcr_cassettes'
  c.hook_into :webmock
end
```

But in my test, when I try to use the headers (after making the request with Faraday):

```
response.headers #=> {}
```

Mind that the body is correct.
