### ISSUE TITLE
config.filter_sensitive_data not filtering refresh_token

### ISSUE THREAD

**Issue by ghost** [vcr/vcr#353]
The refresh_token in  a YouTube API client I'm writing never seems to get filtered.

Example:

```
- request:
    method: post
    uri: https://accounts.google.com/o/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=refresh_token&refresh_token=1%2Fj2xbngqk63lQZ4uIMSUxeGdEvWwPARbrlMou1u13cL0&client_id=<YOUTUBE_KEY>&client_secret=<YOUTUBE_SECRET>
```

Maybe due to encoding? It's recording

```
1%2Fj2xbngqk63lQZ4uIMSUxeGdEvWwPARbrlMou1u13cL0
```

in the cassette when it's actually

```
1/j2xbngqk63lQZ4uIMSUxeGdEvWwPARbrlMou1u13c
```

I can provide the full source if it helps.
