### ISSUE TITLE
VCR don't recognises two uris as equivalent if the parameters change their order.

### ISSUE THREAD

**Issue by cibernox** [vcr/vcr#381]
I don't know if this is intended behavior, but I had a problem after updating VCR/Faraday/Koala (I don't know which one because I updated all at once), but the problem was this.

My cassette was recorded with this URI:

``` yml
- request:
    method: get
    uri: https://graph.facebook.com/fql?q=SELECT+uid+FROM+user+where+third_party_id+%3D+%987zyx%22&access_token=123ABC
    body: .....
```

but, for an unknown reason, after updating my gems, the request I was performing was to this uri:

`https://graph.facebook.com/fql?access_token=123ABC&q=SELECT+uid+FROM+user+where+third_party_id+%3D+%987zyx%22`

As you see, I am performing the same request but with the params in a different order.

As far as I know, the order of the params should not make the url to be considered different (according with the URI specification). I've spotted the place where this can be fixed, but I wanted to know if this was intended and why.

If its not intended, I'll submit a PR to fix that.

Regards.
