### ISSUE TITLE
Recording with AWS-S3 (YAML segfaults)

### ISSUE THREAD

**Issue by rslifka** [vcr/vcr#39]
(on the latest version of VCR and Webmock)

We're using Paperclip's built-in S3 support to store files and query for file existence.  We sometimes see a segfault as described in Issue #4 - (https://github.com/myronmarston/vcr/issues/closed#issue/4.

We're wondering if it's because of the many YAML references in the cassettes generated from S3 traffic?

Thanks!

```
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :delete
    uri: !ruby/regexp /.*amazonaws\.com.*\/str_paperclip_testing\/videos\/\d+\/thumbnails\/image.jpg/
    body: 
    headers: 
      user-agent: 
      - AWS::S3/0.6.2
      authorization: 
      - &id002 !str:AWS::S3::Authentication::Header 
          "@request": &id001 !ruby/object:Net::HTTP::Delete 
            body: 
            body_stream: 
            header: 
              - binary/octet-stream
              authorization: 
              - *id002
              date: 
        "@request": *id001
      content-length: 
      - "0"
      host: 
      - s3.amazonaws.com
```
