### ISSUE TITLE
VCR does not properly recognize Typhoeus redirects

### ISSUE THREAD

**Issue by younker** [vcr/vcr#405]
For my example, the request uri is `https://moz.com` which 301s to `http://moz.com` (the effective_url). However, [the cassette which is saved](https://gist.github.com/younker/7571011995caad4cb814)  records the status code as 200 for a url that is a 301.

[Typhoeus::Response.redirections](http://rubydoc.info/github/typhoeus/typhoeus/Typhoeus/Response/Informations#redirections-instance_method) is an array of response objects which should give you the information you need to accurately record the redirect chain in the cassette.

This is related to https://github.com/vcr/vcr/issues/293.

For ease, here is the cassette I link to above:

```
# spec/cassettes/RedirectChecker/with_single_redirect/redirect_/.yml

---
http_interactions:
- request:
    method: head
    uri: https://moz.com
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Typhoeus - https://github.com/typhoeus/typhoeus
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx
      Content-Type:
      - text/html
      Vary:
      - Accept-Encoding
      Cache-Control:
      - no-cache, must-revalidate, s-maxage=3600
      Expires:
      - Fri, 15 Oct 2004 12:00:00 GMT
      Server-Name:
      - dalmozwww02.dal.moz.com
      Date:
      - Wed, 05 Mar 2014 23:29:32 GMT
      X-Varnish:
      - 542988803 542961567
      Age:
      - '559'
      Via:
      - 1.1 varnish
      Connection:
      - keep-alive
    body:
      encoding: US-ASCII
      string: ''
    http_version: '1.1'
    adapter_metadata:
      effective_url: http://moz.com
  recorded_at: Wed, 05 Mar 2014 23:29:32 GMT

[18] ynkr (#<RedirectChecker>) »  resp = Typhoeus.head('https://moz.com');
[19] ynkr (#<RedirectChecker>) »  resp.response_code
=> 301
```

**Comment by krainboltgreene** [comment]
20 seconds in and I'm starting to gain a dislike for curl-based http clients and redirect problems.

While not a solution I'm contemplating adding a "curl and redirects cause problems" error to VCR when it detects a curl-based HTTP library.

**Comment by konklone** [comment]
So hooking into `typhoeus` instead of `webmock` addresses the issue of VCR being able to follow redirects, but it's not enough to sort out a related issue -- VCR doesn't seem to distinguish properly between Typhoeus calls where `followlocation: true` and `followlocation: false`.

I'm ending up with cassettes with excerpts like this one:

```yaml
- request:
    method: get
    uri: http://whitehouse.gov
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Typhoeus - https://github.com/typhoeus/typhoeus
  response:
    status:
      code: 301
      message: Moved Permanently

  # ... snip ...

- request:
    method: get
    uri: http://whitehouse.gov
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Typhoeus - https://github.com/typhoeus/typhoeus
  response:
    status:
      code: 200
      message: OK
```

And so I can end up with surprisingly non-deterministic results when using VCR with code that might make one kind of request or the other first.

Can VCR uses its Typhoeus integration to distinguish between HTTP requests where the client will follow redirects or not...?
