### ISSUE TITLE
Curl::Easy with follow_location enabled records bad cassettes

### ISSUE THREAD

**Issue by fabn** [vcr/vcr#412]
How to reproduce the issue

``` ruby
require 'rspec'
require 'curb'
require 'webmock'
require 'vcr'

VCR.configure do |c|
  c.cassette_library_dir = File.dirname(__FILE__) 
  c.hook_into :webmock
  c.allow_http_connections_when_no_cassette = false
end

describe 'Failing redirect' do

  def check_url(url)
    Curl::Easy.http_head(url) do |c|
      c.follow_location = true
      c.max_redirects = 2
    end
  end

  it 'should follow redirects' do
    VCR.use_cassette('redirects') do
      check_url('https://github.com/account').response_code.should == 200
    end
  end

end
```

First time the spec pass, with recorded cassette it fails with `UnhandledHTTPRequestError`

```
     Failure/Error: Curl::Easy.http_head(url) do |c|
     VCR::Errors::UnhandledHTTPRequestError:


       ================================================================================
       An HTTP request has been made that VCR does not know how to handle:
         HEAD https://github.com/login?return_to=https://github.com/account
```

Here is cassette content after first run

``` yaml

---
http_interactions:
- request:
    method: head
    uri: https://github.com/account
    body:
      encoding: US-ASCII
      string: ''
    headers: {}
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - GitHub.com
      - GitHub.com
      Date:
      - Tue, 06 May 2014 22:56:21 GMT
      - Tue, 06 May 2014 22:56:21 GMT
      Content-Type:
      - text/html; charset=utf-8
      - text/html; charset=utf-8
      Status:
      - 200 OK
      - 302 Found
      Cache-Control:
      - no-cache
      - no-cache, no-store
      X-Xss-Protection:
      - 1; mode=block
      - 1; mode=block
      X-Frame-Options:
      - deny
      - deny
      Content-Security-Policy:
      - default-src *; script-src https://github.global.ssl.fastly.net https://ssl.google-analytics.com
        https://collector-cdn.github.com; style-src 'self' 'unsafe-inline' 'unsafe-eval'
        https://github.global.ssl.fastly.net; object-src https://github.global.ssl.fastly.net
      - default-src *; script-src https://github.global.ssl.fastly.net https://ssl.google-analytics.com
        https://collector-cdn.github.com; style-src 'self' 'unsafe-inline' 'unsafe-eval'
        https://github.global.ssl.fastly.net; object-src https://github.global.ssl.fastly.net
      Vary:
      - Accept-Encoding
      - Accept-Encoding
      - X-PJAX
      - X-PJAX
      Location:
      - https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Faccount
      Content-Length:
      - '135'
      - '9934'
      X-Github-Request-Id:
      - 02EC8AE6:2A01:2EAD390:53696894
      - 02EC8AE6:2A01:2EAD3E5:53696895
      Strict-Transport-Security:
      - max-age=31536000
      - max-age=31536000
      X-Content-Type-Options:
      - nosniff
      - nosniff
      X-Served-By:
      - 1c0ce1a213af16e49d5419559ef44f50
      - df78b016db710335918cac342ae2a21d
      Set-Cookie:
      - _gh_sess=BAh7BzoPc2Vzc2lvbl9pZEkiJTg0MzJiNjQ4NjQ0OTM4YWE4ODBiNjc2NDU3MzkzMmUxBjoGRUY6EF9jc3JmX3Rva2VuSSIxS2c0U2NjemRHVklRWjh0aVM2aUdNUmt4MFZHVU8zKzd6SmtvUVJ3SS8xaz0GOwZG--fbfa32e3d7e320415e8038505eddee0571a01adb;
        path=/; secure; HttpOnly
      - logged_in=no; domain=.github.com; path=/; expires=Sat, 06-May-2034 22:56:21
        GMT; secure; HttpOnly
      Etag:
      - '"fc7666b7bd0661f9868f5ea1d2495603"'
    body:
      encoding: ASCII-8BIT
      string: ''
    http_version: 
  recorded_at: Tue, 06 May 2014 22:56:21 GMT
recorded_with: VCR 2.9.0
```
