### ISSUE TITLE
vcr 2.x doesn't support username/password in urls?

### ISSUE THREAD

**Issue by joevandyk** [vcr/vcr#416]
This worked fine in vcr 1.11.3, fails on the newest release.

```
An HTTP request has been made that VCR does not know how to handle:
  POST https://brad%40tanga.com%2Ftoken:token@tanga1388184497.zendesk.com/api/v2/tickets.json
  Body: {"ticket":{"requester":{"name":"Joe Van Dyk","email":"joe@example.com"},"subject":"A subject","comment":{"body":"Ticket body"},"tags":["a-subject","ordered_today",null],"custom_fields":[{"id":"21431589","value":"normal"},{"id":"21323344","value":"A reason"},{"id":"21482540","value":"ZendeskOrderUUID"}]}}

VCR is currently using the following cassette:
  - /home/monkey/tanga/shared/gems/zendesk_client/test/vcr_fixtures/zendesk_order.yml
  - :record => :once
  - :match_requests_on => [:method, :uri, :body, :headers]

###### And the VCR cassette at /home/monkey/tanga/shared/gems/zendesk_client/test/vcr_fixtures/zendesk_order.yml that should match the request:

---
http_interactions:
- request:
    method: post
    uri: https://brad%40tanga.com%2Ftoken:token@tanga1388184497.zendesk.com/api/v2/tickets.json
    body:
      encoding: UTF-8
      string: '{"ticket":{"requester":{"name":"Joe Van Dyk","email":"joe@example.com"},"subject":"A
        subject","comment":{"body":"Ticket body"},"tags":["a-subject","ordered_today",null],"custom_fields":[{"id":"21431589","value":"normal"},{"id":"21323344","value":"A
        reason"},{"id":"21482540","value":"ZendeskOrderUUID"}]}}'
    headers:
      Accept:
      - "*/*; q=0.5, application/xml"
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '305'
  response:
    status:
      code: 201
      message: Created
      .....
```
