### ISSUE TITLE
Possible duplication in header data on redirects

### ISSUE THREAD

**Issue by mikebaldry** [vcr/vcr#417]
Think VCR is doing something wrong here given that Location header is defined twice, date is defined twice, etc.. It looks like it could be combining the responses from the redirect in to 1, which is causing things to go wrong.

``` yml

---
http_interactions:
- request:
    method: get
    uri: http://www.alistapart.com/site/rss
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - feedjira http://feedjira.com
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 24 Jun 2014 09:45:34 GMT
      - Tue, 24 Jun 2014 09:45:34 GMT
      - Tue, 24 Jun 2014 09:45:34 GMT
      Server:
      - Apache
      - Apache
      - GSE
      Location:
      - http://alistapart.com/site/rss
      - http://feeds.feedburner.com/alistapart/main
      Cache-Control:
      - max-age=0
      - max-age=0
      - private, max-age=0
      Expires:
      - Tue, 24 Jun 2014 09:45:34 GMT
      - Tue, 24 Jun 2014 09:45:34 GMT
      - Tue, 24 Jun 2014 09:45:34 GMT
      Content-Length:
      - '238'
      - '251'
      Content-Type:
      - text/html; charset=iso-8859-1
      - text/html; charset=iso-8859-1
      - text/xml; charset=UTF-8
      Etag:
      - ZAZAokT9LVoYy3368OJrCQ32up0
      Last-Modified:
      - Tue, 24 Jun 2014 09:45:01 GMT
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Alternate-Protocol:
      - 80:quic
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        ...
    http_version: 
  recorded_at: Tue, 24 Jun 2014 09:45:34 GMT
recorded_with: VCR 2.9.2
```
