### ISSUE TITLE
VCR returns responses from other cassettes instead of recording new interactions

### ISSUE THREAD

**Issue by HermanHiddema** [vcr/vcr#425]
I'm not sure if this is a VCR bug, or the result of some kind of interaction with webmock, but I'm having an issue where VCR does not record a new request, but instead returns the response from another cassette that has been recorded earlier.

I'm using
- VCR 2.9.2
- webmock 1.15.2
- rspec 3.0.0
- curb 0.8.5
- ruby 2.1.0p0

I'm writing tests for a gem that uses Curl::Easy to connect to an external API, and want to add a test that the API respons with 401 unauthorized when I use wrong credentials, and that my code handles that gracefully.

My VCR config looks like:

```
VCR.configure do |c|
    c.cassette_library_dir = 'spec/vcr/cassettes'
    c.default_cassette_options = { :record => :new_episodes }
    c.hook_into :webmock # or :fakeweb
    c.configure_rspec_metadata!
    c.debug_logger = $stderr
end
```

I have a bunch of tests, and just added a new one:

```
describe KlikEnVerzend::Document do

    let(:document) { KlikEnVerzend::Document.new(path: File.expand_path('spec/fixtures/pdfs/1page.pdf')) }

    describe '#send_pdf', :vcr do

        ....snip other tests....

        context "authentication failure" do
            it "responds with 401 status" do
                KlikEnVerzend.configuration.password='wrong'
                expect{document.send_pdf}.to change(document, :http_response_code).to(401)
            end    
        end
    end
```

When I run this, it creates a new file `spec/vcr/cassettes/KlikEnVerzend_Document/_send_pdf/authentication_failure/responds_with_401_status.yml`

Now this file should contain a response with an HTTP response code of 401, and content that looks something like:

```
<?xml version="1.0" encoding="utf-8"?>
<xml><error>The provided credentials are incorrect.</error></xml>
```

Because that is the response that I get when I run a minimalized test script like this:

```
require 'curb'
curl = Curl::Easy.new do |curl|
    curl.username = 'payttest'
    curl.password = 'wrong'
    curl.http_auth_types = :basic
    curl.url = 'https://api-testing.postnldocumentoplossingen.nl/api/file'
    curl.multipart_form_post = true
    curl.verbose = true
end

curl.http_post(Curl::PostField.file('file', File.expand_path('klik_en_verzend/spec/fixtures/pdfs/1page.pdf')), Curl::PostField.content('sided','1'))
puts curl.body_str
```

However, the content of the YAML file are:

```

---
http_interactions:
- request:
    method: post
    uri: https://payttest:wrong@api-testing.postnldocumentoplossingen.nl/api/file
    body:
      encoding: US-ASCII
      string: file=%2Fhome%2Fherman%2Fdevelopment%2Fpayt%2Fklik_en_verzend%2Fspec%2Ffixtures%2Fpdfs%2F1page.pdf&sided=1
    headers: {}
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 16 Jul 2014 15:24:50 GMT
      Server:
      - Apache/2
      X-Powered-By:
      - PHP/5.4.23
      Content-Length:
      - '416'
      Vary:
      - Accept-Encoding,User-Agent
      Content-Type:
      - application/xml
    body:
      encoding: ASCII-8BIT
      string: |
        <?xml version="1.0" encoding="utf-8"?>
        <xml><message>The file will be sent with the following data</message><data><international>0</international><sided>1</sided><pages>4</pages><recipients>1</recipients><pages_per_recipient>4</pages_per_recipient><return_address></return_address><original_name>4page.pdf</original_name><reference>0</reference><request_id>c5aa9299dc781864d1db67678127cc96</request_id></data></xml>
    http_version: 
  recorded_at: Thu, 17 Jul 2014 08:22:34 GMT
recorded_with: VCR 2.9.2
```

Note that VCR's recorded_at time is very different from the Date header in the response. Also, the `original_name` field in the returned XML does not match the filename from the request.

It turns out that the content of the entire response section are identical to those from another cassette:

```

---
http_interactions:
- request:
    method: post
    uri: https://payttest:testpasswd@api-testing.postnldocumentoplossingen.nl/api/file
    body:
      encoding: US-ASCII
      string: file=%2Fhome%2Fherman%2Fdevelopment%2Fpayt%2Fklik_en_verzend%2Fspec%2Ffixtures%2Fpdfs%2F4page.pdf&sided=1
    headers: {}
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 16 Jul 2014 15:24:50 GMT
      Server:
      - Apache/2
      X-Powered-By:
      - PHP/5.4.23
      Content-Length:
      - '416'
      Vary:
      - Accept-Encoding,User-Agent
      Content-Type:
      - application/xml
    body:
      encoding: ASCII-8BIT
      string: |
        <?xml version="1.0" encoding="utf-8"?>
        <xml><message>The file will be sent with the following data</message><data><international>0</international><sided>1</sided><pages>4</pages><recipients>1</recipients><pages_per_recipient>4</pages_per_recipient><return_address></return_address><original_name>4page.pdf</original_name><reference>0</reference><request_id>c5aa9299dc781864d1db67678127cc96</request_id></data></xml>
    http_version: 
  recorded_at: Wed, 16 Jul 2014 15:24:53 GMT
recorded_with: VCR 2.9.2
```

This is the file `spec/vcr/cassettes/KlikEnVerzend_Document/_send_pdf/four_pages/can_be_printed_double_sided.yml`, which is the result of another test (in the same `describe #send_pdf` section):

```
    context "four pages" do
        let(:document) { KlikEnVerzend::Document.new(path: File.expand_path('spec/fixtures/pdfs/4page.pdf')) }

        it "can be printed double sided" do
            document.double_sided = true
            expect{document.send_pdf}.to change(document, :http_response_code).to(200)
        end
    end
```

If I remove the newly created cassette and rerun RSpec, it will again not return a 401 response, but will have the response from a random other cassette (probably the previous test from rspec's randomized order)

The code for KlikEnVerzend::Document#send_pdf uses a curl http_post call identical to the one in the minimalized tests script given earlier.
