### ISSUE TITLE
Timestamps are not being ignored, VCR continues to make lots of episodes.

### ISSUE THREAD

**Issue by ellmo** [vcr/vcr#449]
This is the portion of my `test_helper.rb` which should clearly tell VCR not to record new casettes, if an already recorded one differs only in timestamp from the new request.

``` ruby
uri_without_timestamp = VCR.request_matchers.uri_without_param(:timestamp)
VCR.configure do |c|
  c.cassette_library_dir = './cassettes'
  c.hook_into :webmock, :faraday
  c.debug_logger = File.open('./cassettes/debug.txt', 'w+')
  c.register_request_matcher :ignored_timestamp do |request_1, request_2|
    URI(request_1.uri).query.gsub(/&?timestamp=\d*/,'') == URI(request_2.uri).query.gsub(/&?timestamp=\d*/,'')
  end
  c.default_cassette_options = { record: :new_episodes, match_requests_on: [:method, :uri, uri_without_timestamp] }
end
```

However new episodes are being recorded... even with exactly the same timestamp (not to mention the point is to ignore it altogether).

``` yaml
- request:
    method: get
    uri: https://maps.googleapis.com/maps/api/timezone/json?location=35.303611,-120.376667&sensor=false&timestamp=1414500825
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json; charset=UTF-8
      Date:
      - Tue, 28 Oct 2014 12:53:45 GMT
      Pragma:
      - no-cache
      Expires:
      - Fri, 01 Jan 1990 00:00:00 GMT
      Cache-Control:
      - no-cache, must-revalidate
      Access-Control-Allow-Origin:
      - "*"
      Server:
      - mafe
      X-Xss-Protection:
      - 1; mode=block
      X-Frame-Options:
      - SAMEORIGIN
      Alternate-Protocol:
      - 443:quic,p=0.01
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: |
        {
           "dstOffset" : 3600,
           "rawOffset" : -28800,
           "status" : "OK",
           "timeZoneId" : "America/Los_Angeles",
           "timeZoneName" : "Pacific Daylight Time"
        }
    http_version: 
  recorded_at: Tue, 28 Oct 2014 12:53:45 GMT
- request:
    method: get
    uri: https://maps.googleapis.com/maps/api/timezone/json?location=35.303611,-120.376667&sensor=false&timestamp=1414500825
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json; charset=UTF-8
      Date:
      - Tue, 28 Oct 2014 12:53:45 GMT
      Pragma:
      - no-cache
      Expires:
      - Fri, 01 Jan 1990 00:00:00 GMT
      Cache-Control:
      - no-cache, must-revalidate
      Access-Control-Allow-Origin:
      - "*"
      Server:
      - mafe
      X-Xss-Protection:
      - 1; mode=block
      X-Frame-Options:
      - SAMEORIGIN
      Alternate-Protocol:
      - 443:quic,p=0.01
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: |
        {
           "dstOffset" : 3600,
           "rawOffset" : -28800,
           "status" : "OK",
           "timeZoneId" : "America/Los_Angeles",
           "timeZoneName" : "Pacific Daylight Time"
        }
    http_version: 
  recorded_at: Tue, 28 Oct 2014 12:53:45 GMT
```

If I change `record: :new_episodes` to `record: :once`, I will get a lot of these:

```
Under the current configuration VCR can not find a suitable HTTP interaction to replay and is prevented from recording new requests.
```

Doesn't matter wether I use VCR's `uri_without_param` or my regex matcher. I even tried to load a separate cassette for every single test piece, thinking maybe I'm not allowed to reuse a casette created in test **A** to stop requests from going out of test **B**, but no, VCR keeps appending more and more episodes even when I split into 5 cassettes.
