### ISSUE TITLE
VCR: How to Update Existing fixtures

### ISSUE THREAD

**Issue by sithara** [vcr/vcr#473]
Hi, I'm kind of new to this.I have an existing vcr fixture in my app.I would like to add a new one.How do I it?The relish site is down :( .Can somebody help?

**Comment by krainboltgreene** [comment]
I'm assuming this is the documentation you're looking for: 

https://github.com/vcr/vcr/blob/master/features/cassettes/automatic_re_recording.feature

**Comment by sithara** [comment]
@krainboltgreene  Thanks for the prompt reply :)
I really don't want to re-record the cassette.I would want to add a new request response to the my fixture and reference that one.Is something like that possible?

**Comment by krainboltgreene** [comment]
Each cassette is supposed to be a single request (ideally). Can you give me
your code as an example?

**Comment by sithara** [comment]
```
---
http_interactions:
- request:
    method: post
    uri: xxxxxxxxxxxxx
    body:
      encoding: US-ASCII
      string: address[street1]=xxxx
  response:
    status:
      code: 200
      message: OK
    body:
      encoding: US-ASCII
      string: ! '{"address":{"id":"eerier" }'
- request:
    method: post
    uri: xxxxxxxxxxxxx
    body:
      encoding: US-ASCII
      string: address[street1]=gggg
  response:
    status:
      code: 200
      message: OK
    body:
      encoding: US-ASCII
      string: ! '{"address":{"id":"22222" }'
```
