### ISSUE TITLE
VCR/WebMock/EM-HTTP-Request compressed responses issue

### ISSUE THREAD

**Issue by smileart** [vcr/vcr#615]
**Problems I'm experiencing**:

When I use VCR with WebMock and EM-HTTP-Request I get such an issue: when I request a web-resource which response contains compressed gzip data, on the first run VCR records a response to the cassette (already decoded by EM-HTTP-Request, which is its default behaviour) but keeps `Content-Encoding: gzip` header, so on the next run when the cassette is used, it mocks all the data (decoded one), but with the header which forces libraries to decode it again, so since it's already not a gzip binary data it surely fails with a `Content-decoder error`. **Important notice**: it happens and should be reproduced and tested on a real request only (with `:real_requests_only`).

**Environment & Versions**:

* VCR: 3.0.3
* WebMock: 2.1.0
* EM-HTTP-Request: 1.1.5
* OS X: macOS Sierra 10.12 (16A323 / x86_64-darwin15)
* Ruby: 2.3.1p112 (2016-04-26 revision 54768)

**Simple script to reproduce**:

```ruby
require 'vcr'
require 'em-http-request'
require 'minitest/autorun'

VCR.configure do |c|
  c.default_cassette_options = { record: :once } # , decode_compressed_response: true }
  c.cassette_library_dir = "./vcr_cassettes/"
  c.hook_into :webmock
end

describe 'Reproduce VCR/Webmock issue' do
  before do
    VCR.insert_cassette name
  end

  after do
    VCR.eject_cassette
  end

  it 'Makes requests' do
    EventMachine.run do
      http = EventMachine::HttpRequest.new('http://httpbin.org/gzip').get

      http.errback { p http.error; EM.stop }

      http.callback {
        http.response_header.status.must_equal 200
        EM.stop
      }
    end
  end
end
```

On the first run it outputs:

```
# Running:
.
Finished in 0.265574s, 3.7654 runs/s, 3.7654 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

And produces file like this (`./vcr_cassettes/test_0001_makes_requests.yml`):

```yaml
---
http_interactions:
- request:
    method: get
    uri: http://httpbin.org/gzip
    body:
      encoding: US-ASCII
      string: ''
    headers: {}
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx
      Date:
      - Mon, 31 Oct 2016 00:00:00 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '175'
      Connection:
      - close
      Content-Encoding:
      - gzip
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Credentials:
      - 'true'
    body:
      encoding: UTF-8
      string: "{\n  \"gzipped\": true, \n  \"headers\": {\n    \"Accept-Encoding\":
        \"gzip, compressed\", \n    \"Host\": \"httpbin.org\", \n    \"User-Agent\":
        \"EventMachine HttpClient\"\n  }, \n  \"method\": \"GET\", \n  \"origin\":
        \"0.0.0.0\"\n}\n"
    http_version: 
  recorded_at: Mon, 31 Oct 2016 00:00:00 GMT
recorded_with: VCR 3.0.3
```

On the second run though it outputs this:

```
# Running:

"Content-decoder error"
.
Finished in 0.062267s, 16.0599 runs/s, 0.0000 assertions/s.

1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

**Possible fixes**:

Sure it could be fixed either on WebMock side by deleting a header [here](https://github.com/webmock/webmock/blob/master/lib/web_mock/adapters/em_http_request.rb#L70) with something like:

```ruby
if @req.decoding && @req.compressed
  webmock_response.headers.delete('Content-Encoding')
end
```

which is NOT correct, since someone would like to mock a request with such a header (even though EM-HTTP-Request already responded on this step with the uncompressed data 😕) or it could be fixed somwhere in VCR, like [before recording](https://github.com/vcr/vcr/blob/master/lib/vcr/library_hooks/webmock.rb#L147) a response.

I hope this is enough data to reproduce the issue. At the same time though I do not deny the possibility that I'm doing something wrong. Correct me if it's the case and it's neither VCR nor Webmock issue.
