### ISSUE TITLE
Using ENV in cassette yaml

### ISSUE THREAD

**Issue by roykolak** [vcr/vcr#675]
Curious if anyone has advice or experience with ENV vars in the cassette yaml. Currently doing something like this....
```yml
---
http_interactions:
- request:
    method: post
    uri: ENV["VAR_NAME"]
    body: ....
```

and then in the `spec_helper.rb`

```rb
VCR.configure do |c|
  #...
  c.filter_sensitive_data('ENV["VAR_NAME"]') { ENV["VAR_NAME"] }
end
```

But this is not ideal as we need to remember to add new `filter_sensitive_data` calls for future ENV vars. Thoughts, advice?
