### ISSUE TITLE
Convert YAML into JSON format.

### ISSUE THREAD

**Issue by zw963** [vcr/vcr#699]
Hi, I have many VCR cassette, which use default YAML format, Following is a example:

```yaml
---
http_interactions:
- request:
    method: get
    uri: http://dev.cms.ikcrm.com:3000/v1/promotion_pushers/1.json
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Access-Token:
      - 0sFc4mpJfhCRO3FQ7BqsZTeCsmbylCxdKz44Qd3Zr8UbpLdmoNL0ORRmx-fQa3ZKlS8
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      Content-Type:
      - application/json; charset=utf-8
      Cache-Control:
      - no-store, must-revalidate, private, max-age=0
      X-Request-Id:
      - abdaf38b-ced7-4b60-8ce3-f1aa407d1625
      X-Runtime:
      - '0.035722'
      Set-Cookie:
      - __profilin=p%3Dt; path=/
      - __profilin=p%3Dt; path=/
      - __profilin=p%3Dt; path=/
      X-Miniprofiler-Ids:
      - '["tw8quysfy0f2u7lzrthn","2h7yftj9qjhdtemycb52","iejvdsjt0dkg82d6tjbu","mi3lqy4an8htjdopin58","r0bheyfk910ka1jchdmq","v0ewqb6jqmlqkv36zm2m","e87fnd0weevpx5xyvs4g","mwcq4mzuqao0cbpa26qi","qo8qq1i8zhs6qjvx885y","ulbln6s6qg5k8mqaa0c7"]'
      Connection:
      - close
      Server:
      - thin
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        eyJjb2RlIjoiMjAwIiwibXNnIjoib2siLCJkYXRhIjp7InByb21vdGlvbl9w
        dXNoZXIiOnsiaWQiOiIxIiwiaXNfYWxsIjpmYWxzZSwiaW1hZ2VfdXJsIjoi
        L2ltYWdlcy9vcmlnaW5hbC9taXNzaW5nLnBuZyIsIm9yZ2FuaXphdGlvbl9p
        ZHMiOlsxLDIsM10sInB1c2hlcl90eXBlIjoi5paH5pys5Y2h54mHIiwiYnV0
        dG9uX2xpbmtfdHlwZSI6IuaZrumAmumTvuaOpSIsImV4cGVjdGVkX2NvcnBf
        Y291bnQiOjAsImV4cGVjdGVkX3VzZXJfY291bnQiOjAsInRpdGxlIjoiYWRz
        ZmRhc2YiLCJkZXNjcmlwdGlvbiI6ImFzZGZhc2RmYXNkZmFzIiwiYnV0dG9u
        X3RleHQiOiLor6bmg4UiLCJidXR0b25fbGluayI6Imh0dHA6Ly93d3cuYmFp
        ZHUuY29tIiwicHJvZHVjdF90eXBlIjoi5Yqx6ZSAQ1JNIiwicm9sZV90eXBl
        Ijoi5aSp5YaF5LiN5rS76LeD55So5oi3IiwidXNlcl9ub19hY3Rpdml0eV9k
        YXlzIjpudWxsfX19
    http_version: 
  recorded_at: Sat, 17 Mar 2018 12:00:39 GMT
recorded_with: VCR 4.0.0
```

I want to change this cassette to use JSON format which have no encoding response, I can 
edit it conveniently.

But, i spent two hours to try resolve this, it is still not work.

When I load this yaml with `YAML.load`, I always got following response string:

```
{"encoding"=>"ASCII-8BIT",
        "string"=>
         "{\"code\":\"200\",\"msg\":\"ok\",\"data\":{\"promotion_pusher\":{\"id\":\"1\",\"is_all\":false,\"image_url\":\"/images/original/missing.png\",\"organization_ids\":[1,2,3],\"pusher_type\":\"\xE6\x96\x87\xE6\x9C\xAC\xE5\x8D\xA1\xE7\x89\x87\",\"button_link_type\":\"\xE6\x99\xAE\xE9\x80\x9A\xE9\x93\xBE\xE6\x8E\xA5\",\"expected_corp_count\":0,\"expected_user_count\":0,\"title\":\"adsfdasf\",\"description\":\"asdfasdfasdfas\",\"button_text\":\"\xE8\xAF\xA6\xE6\x83\x85\",\"button_link\":\"http://www.baidu.com\",\"product_type\":\"\xE5\x8A\xB1\xE9\x94\x80CRM\",\"role_type\":\"\xE5\xA4\xA9\xE5\x86\x85\xE4\xB8\x8D\xE6\xB4\xBB\xE8\xB7\x83\xE7\x94\xA8\xE6\x88\xB7\",\"user_no_activity_days\":null}}}"}
```

But, the expected result is:

```
"string":"{\"code\":\"200\",\"msg\":\"ok\",\"data\":{\"promotion_pusher\":{\"id\":\"1\",\"is_all\":false,\"image_url\":\"/images/original/missing.png\",\"organization_ids\":[1,2,3],\"pusher_type\":\"文本卡片\",\"button_link_type\":\"普通链接\",\"expected_corp_count\":0,\"expected_user_count\":0,\"title\":\"adsfdasf\",\"description\":\"asdfasdfasdfas\",\"button_text\":\"详情\",\"button_link\":\"http://www.baidu.com\",\"product_type\":\"励销CRM\",\"role_type\":\"天内不活跃用户\",\"user_no_activity_days\":null}}}"},"http_version":null},"recorded_at":"Sat, 17 Mar 2018 12:07:58 GMT"}],"recorded_with":"VCR 4.0.0"}
```

`YAML.load` or `YAML.load_file` i never found args about encoding, am I missing something here?

Thanks.
