### ISSUE TITLE
Not recording cassettes & stuck

### ISSUE THREAD

**Issue by victorhazbun** [vcr/vcr#702]
## Description
I'm consuming the Twitter API using the [twitter gem](https://github.com/sferik/twitter). 
For some reason the test gets stuck and it won't record/save the cassette.

## Problems
- VCR is getting stuck
- Won't save cassettes

## Questions
- Does this has something to be with the twitter gem?
- Could this be related to my Rails version?
- Could this be associated to my RSpec configuration?

#### `Gemfile`
```
gem "rails", "5.2.0rc1"
gem "twitter"

group :test do
  gem "rspec-rails"
  gem "vcr"
  gem "webmock"
end
```

#### `spec/support/vcr.rb`

```
RSpec.configure do |config|
  VCR.configure do |c|
    c.cassette_library_dir = "spec/cassettes"
    c.hook_into :webmock
    c.configure_rspec_metadata!
    c.ignore_localhost = true
  end
end
```

#### `spec/models/avatar_adapter_spec.rb`

```
require "rails_helper"

RSpec.describe User do

  it "accurately receives image url", :vcr do
    user = instance_double(User, twitter_handle: "victorhazbun")
    adapter = AvatarAdapter.new(user)
    url = "http://pbs.twimg.com/profile_images/935204734050463745/JcNp7zAf_bigger.jpg"
    expect(adapter.image_url).to eq(url)
  end
end

```

#### `app/models/avatar_adapter.rb`

```
class AvatarAdapter
  attr_accessor :user

  def initialize(user)
    @user = user
  end

  def client
    @client ||= begin
      Twitter::REST::Client.new(
        consumer_key: Rails.application.credentials.twitter_api_key,
        consumer_secret: Rails.application.credentials.twitter_api_secret)
    end
  end

  def image_url
    client.user(user.twitter_handle).profile_image_uri(:bigger).to_s
  end
end

```

**Comment by rusikf** [comment]
I have the same problem, any ideas ?

**Comment by rusikf** [comment]
The problem is with oauth2 token request, for unknown request response is nil with vcr, so mime error raised. But in real request response is not nil, so it works

**Comment by tehPlayer** [comment]
I had same issue and found a solution.

The problem lies in new HTTP gem version (3.0.0).
Issue source is in `lib/twitter/rest/request.rb:37`
```
        response_body = response.body.empty? ? '' : symbolize_keys!(response.parse)
```

Response body isn't empty as you mentioned, thats why the `response.parse` is getting called. This method will check MimeType this way:

```
def parse(as = nil)
  MimeType[as || mime_type].decode to_s
end
```

As we aren't providing any arguments, then we use method `mime_type` which is meta-programmed, using headers.
Therefore, the solution is to provide header `{'Content-Type' => 'application/json'}` (or different, like `text/plain`, depends what are you passing).

**Comment by mendab1e** [comment]
@rusikf Have you solved the problem? I tried to use a solution from @tehPlayer, however it doesn't work for me. Still can't get a bearer token with VCR. 

First of all, I've tried to send `application/json` as a param `response.parse('application/json')`, it let me to the error: `JSON::ParserError: A JSON text must at least contain two octets!`. In the cassette file I found a request timeout. 

```
  response:
    status:
      code: 408
      message: Request Timeout
    headers:
      Connection:
      - close
      Content-Length:
      - '0'
      Date:
      - Tue, 24 Apr 2018 00:29:09 GMT
      Server:
      - tsa_o
      X-Connection-Hash:
      - bc29ede64d29799114e77a46539eea80
    body:
      encoding: ASCII-8BIT
      string: ''
    http_version: 
  recorded_at: Tue, 24 Apr 2018 00:29:09 GMT
recorded_with: VCR 4.0.0
```
This is really strange, because when I do all these steps from irb, it works fine and I can get a bearer token. Also I think that we don't need to change a header or send a strict MIME-type, because if VCR would get a proper response, there wouldn't be a problem with the MIME-type
