### ISSUE TITLE
VCR performing HTTP requests even when fixture is present

### ISSUE THREAD

**Issue by sirupsen** [vcr/vcr#75]
With the test:

``` ruby
test 'test vcr' do
  VCR.use_cassette("test") do
    Excon.get("http://google.com")
  end
end
```

And config:

``` ruby
# for some reason vcr isn't mocking if it's not explicitly allowed
VCR::HttpStubbingAdapters::Excon.http_connections_allowed = true

VCR.config do |c|
  c.cassette_library_dir = 'test/cassettes'
  c.stub_with :fakeweb
  c.default_cassette_options = {
    :record => :once
  }
end
```

Running the test twice results in this fixture:

``` yaml
--- 
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :get
    uri: http://google.com:80/
    body: 
    headers: 
  response: !ruby/struct:VCR::Response 
    status: !ruby/struct:VCR::ResponseStatus 
      code: 301
      message: 
    headers: 
      location: 
      - http://www.google.com/
      content-type: 
      - text/html; charset=UTF-8
      date: 
      - Sat, 02 Jul 2011 23:17:03 GMT
      expires: 
      - Mon, 01 Aug 2011 23:17:03 GMT
      cache-control: 
      - public, max-age=2592000
      server: 
      - gws
      content-length: 
      - "219"
      x-xss-protection: 
      - 1; mode=block
    body: |
      <HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
      <TITLE>301 Moved</TITLE></HEAD><BODY>
      <H1>301 Moved</H1>
      The document has moved
      <A HREF="http://www.google.com/">here</A>.
      </BODY></HTML>

    http_version: 
- !ruby/struct:VCR::HTTPInteraction 
  request: !ruby/struct:VCR::Request 
    method: :get
    uri: http://google.com:80/
    body: 
    headers: 
  response: !ruby/struct:VCR::Response 
    status: !ruby/struct:VCR::ResponseStatus 
      code: 301
      message: 
    headers: 
      location: 
      - http://www.google.com/
      content-type: 
      - text/html; charset=UTF-8
      date: 
      - Sat, 02 Jul 2011 23:17:06 GMT
      expires: 
      - Mon, 01 Aug 2011 23:17:06 GMT
      cache-control: 
      - public, max-age=2592000
      server: 
      - gws
      content-length: 
      - "219"
      x-xss-protection: 
      - 1; mode=block
    body: |
      <HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
      <TITLE>301 Moved</TITLE></HEAD><BODY>
      <H1>301 Moved</H1>
      The document has moved
      <A HREF="http://www.google.com/">here</A>.
      </BODY></HTML>

    http_version: 
```

I.e. it has run the request twice. I tried both `fakeweb` and `webmock`, result is the same for both. I tested it with `curb` too, same result.
