### ISSUE TITLE
Can I stabilize image_url mounted with carrierwave in the request body?

### ISSUE THREAD

**Issue by f-teruhisa** [vcr/vcr#830]
Hi, there.
I have a question about how to use this gem.

I want to stab value of the carrierwave mounted image_url in request_body.

Because the value of the carrierwave mounted image_url will change each time test with Rspec. If the value of image_url in request body is different when searching for the cassett, vcr cannot find the cassett.

Sorry, but this question includes about [carrierwave](https://github.com/carrierwaveuploader/carrierwave). 
If already have a solution, please let me know.

- Faraday Request Log

```
http_interactions:
- request:
    method: post
    uri: https://example.com/users/
    body:
      encoding: UTF-8
      # value of 'xxxxxxxxxxxxxxx.jpg' will be changed each time in test
      string: '{"user":{"id":1,"name":"Test","image_url":'/uploads/sample/image/1/xxxxxxxxxxxxxxx.jpg'}}'
    headers:
      User-Agent:
      - Faraday v0.17.3
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
```

- Faraday Request Code

```
connection = Faraday.new('https://example.com/users/') do |builder|
      builder.request :json
      builder.adapter Faraday.default_adapter
end

connection.post do |conn|
      conn.headers["Content-Type"] = "application/json"
      conn.body = json.to_json
end
```
