### ISSUE TITLE
filter_sensitive_data on header key not replacing header value

### ISSUE THREAD

**Issue by scalp42** [vcr/vcr#898]
Hi folks,

I'm probably missing something but I'm simply trying to filter out the value of a header:

```ruby
    config.filter_sensitive_data('<UNICORN>') do |interaction|
      interaction.request.headers['X-Ops-Userid']
    end
```

The cassette content:

```yaml
http_interactions:
- request:
    method: get
    uri: blabla
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - application/json
      User-Agent:
      - ChefAPI Ruby Gem 0.10.10
      Content-Type:
      - application/json
      X-Chef-Version:
      - 11.4.0
      X-Ops-Userid:
      - anthony
```

VCR config:

```ruby
  VCR.configure do |config|
    config.cassette_library_dir = "fixtures"
    config.hook_into :webmock
    config.ignore_localhost = false
    config.allow_http_connections_when_no_cassette = false
    config.filter_sensitive_data('<UNICORN>') do |interaction|
      interaction.request.headers['X-Ops-Userid']
    end
  end
```

I've tried to print the `X-Ops-Userid` as well to confirm it's just `anthony`.

`config.filter_sensitive_data('<UNICORN>') { 'anthony' }` would do but that would defeat the purpose as in my case it'd be a secret and non deterministic.

Ruby `2.7.3p183`
Gem `6.0.0`

Thank you in advance!
