### ISSUE TITLE
Parsing snapshot/cassette with rest-client 2.1.0 returns invalid encoding text

### ISSUE THREAD

**Issue by dangnm** [vcr/vcr#987]
I upgraded rest-client from 2.0.2 to 2.1.0 and the response.body returned incorrectly with a snapshot recorded in VCR 4.0.0. 

Maybe the root cause came from this update https://github.com/rest-client/rest-client/pull/597
Is there any chance I can make my snapshot work with rest-client 2.1.0?

```ruby
      before do
        VCR.use_cassette('Github.fetch_data') do
           response = RestClient.get(uri.to_s, headers)
           parsed_response = ::JSON.parse(response.body)
        end
      end
```

With rest-client (2.1.0)

```ruby
(byebug) response.body
"\uFFFF\x8F\b\u0000\u0000\u0000\u0000\u0000\u0000\u000F ....
```
With rest-client (2.0.2)

```ruby
(byebug) puts response.body
[{"id":1234567,"node_id":"ABCDEF","name":"ABCD","full_name":"abc/test","private":false,"owner":{"login":"test","id":123456,"node_id":"1235567777
```

```
require 'vcr'

VCR.configure do |config|
  config.cassette_library_dir = 'spec/vcr'
  config.hook_into :webmock, :faraday
end
```

```
---
http_interactions:
- request:
    method: get
    uri: https://api.github.com/orgs/test/repos?page=1
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - "*/*"
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.2 (darwin15.6.0 x86_64) ruby/2.3.3p222
      Authorization:
      - Basic <GITHUB_TOKEN>
      Host:
      - api.github.com
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 30 Nov 2018 07:51:07 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Server:
      - GitHub.com
      Status:
      - 200 OK
      X-Ratelimit-Limit:
      - '5000'
      X-Ratelimit-Remaining:
      - '1234'
      X-Ratelimit-Reset:
      - '12345678'
      Cache-Control:
      - private, max-age=60, s-maxage=60
      Vary:
      - Accept, Authorization, Cookie, X-GitHub-OTP
      - Accept-Encoding
      Etag:
      - W/"12345678"
      X-Oauth-Scopes:
      - repo
      X-Accepted-Oauth-Scopes:
      - ''
      X-Github-Media-Type:
      - github.v3; format=json
      Link:
      - <https://api.github.com/organizations/12345678/repos?page=2>; rel="next", <https://api.github.com/organizations/12345678/repos?page=6>;
        rel="last"
      Access-Control-Expose-Headers:
      - ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining,
        X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval,
        X-GitHub-Media-Type
      Access-Control-Allow-Origin:
      - "*"
      Strict-Transport-Security:
      - max-age=31536000; includeSubdomains; preload
      X-Frame-Options:
      - deny
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Referrer-Policy:
      - origin-when-cross-origin, strict-origin-when-cross-origin
      Content-Security-Policy:
      - default-src 'none'
      Content-Encoding:
      - gzip
      X-Github-Request-Id:
      - FFFF:FFFFF:FFFFFF:FFFFFF:FFFFFFFF
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        AAAAAAAAA+234sdfsdf245234r2...
    http_version: 
  recorded_at: Fri, 30 Nov 2018 07:51:07 GMT
recorded_with: VCR 4.0.0

```

Ruby 2.6.10p210
Gem 6.1.0
HTTP faraday (1.10.3)
Mock webmock (3.18.1)
Rspec 3.12.0
