### ISSUE TITLE
warning: lambda without a literal block is deprecated; use the proc without lambda instead in VCR::Request::FiberAware#to_proc

### ISSUE THREAD

**Issue by hirokishirai** [vcr/vcr#992]
Thank you all for developing and maintaining an excellent testing solution.

When setting `Warning[:deprecated] = true` and writing `VCR.use_cassette(request.uri, &request)` within the block of `config.around_http_request`, then running rspec, the following warning occurs:

```
/path/to/rbenv/versions/3.0.4/lib/ruby/3.0.0/delegate.rb:89: warning: lambda without a literal block is deprecated; use the proc without lambda instead
```
It appears this is triggered at https://github.com/vcr/vcr/blob/v6.2.0/lib/vcr/structs.rb#L307. However, it seems there shouldn't be any issues as the `to_proc` method here returns a `lambda with a block`. What's even more peculiar is that the Proc generated by `lambda { proceed }` within this `to_proc` method isn't a lambda.

```ruby
# When VCR.use_cassette(request.uri, &request) is called
# For some reason, block.lambda? becomes false in vendor/bundle/ruby/3.0.0/gems/vcr-6.2.0/lib/vcr.rb#use_cassette
    184: def use_cassette(name, options = {}, &block)
    185:   binding.pry
 => 186:   unless block
[1] pry(VCR)> block.lambda?
=> false
```
Normally, the following should return true:

```ruby
class Hoge
  def to_proc
    lambda { proceed }
  end
  def proceed
    Fiber.yield
  end
end

def lambda?(&block)
  block.lambda?
end
lambda?(&Hoge.new)
# => true
```

I couldn't comprehend what was happening.

While replacing `VCR.use_cassette(request.uri, &request)` with `VCR.use_cassette(request.uri) { request.proceed }` seems to prevent the warning, I'm not sure if this is the correct way to rectify the issue.

Do you understand what is happening?

<details>

<summary>To replicate issue</summary>

```ruby
# spec_helper.rb
require "vcr"
Warning[:deprecated] = true
VCR.configure do |config|
  config.cassette_library_dir = 'spec/vcr'
  config.hook_into :webmock
  config.allow_http_connections_when_no_cassette = false
  config.around_http_request do |request|
    VCR.use_cassette(request.uri, &request)
  end
end

# spec/requests/nasa_rspec.rb
require 'rails_helper'
require 'uri'
require 'net/http'

describe 'GET /posts' do
  it "gets a response from an api" do
    response = JSON.parse(Net::HTTP.get_response(URI('https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY')).body)
    expect(response).to have_key('date')
  end
end
```
<details>
<summary>spec/vcr/model/api_response.yml</summary>

```yml
---
http_interactions:
- request:
    method: get
    uri: https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Host:
      - api.nasa.gov
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 16 Oct 2023 11:58:08 GMT
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - X-RateLimit-Limit, X-RateLimit-Remaining
      Age:
      - '0'
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains; preload
      Vary:
      - Accept-Encoding
      Via:
      - http/1.1 api-umbrella (ApacheTrafficServer [cMsSf ])
      X-Api-Umbrella-Request-Id:
      - cb71cs19r58r2vbdmofg
      X-Cache:
      - MISS
      X-Ratelimit-Limit:
      - '40'
      X-Ratelimit-Remaining:
      - '38'
      X-Vcap-Request-Id:
      - c92c6865-cf56-4e88-4a2f-5ab3e6aa5eb8
      X-Frame-Options:
      - DENY
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
    body:
      encoding: ASCII-8BIT
      string: '{"copyright":"\nJerry Zhang (left), \nBaolong Chen (photographer) &
        Amber Zhang (right)\n","date":"2023-10-16","explanation":"She knew everything
        but the question. She was well aware that there would be a complete annular
        eclipse of the Sun visible from their driving destination: Lake Abert in Oregon.  She
        knew that the next ring-of-fire eclipse would occur in the USA only in 16
        more years, making this a rare photographic opportunity.  She was comfortable
        with the plan: that she and her boyfriend would appear in front of the eclipse
        in silhouette, sometimes alone, and sometimes together.  She knew that the
        annular phase of this eclipse would last only a few minutes and she helped
        in the many hours of planning.  She could see their friend who set up the
        camera about 400 meters away at the bottom of a ridge.  What she didn''t know
        was the question she would be asked. But she did know the answer: \"yes\".   Album:
        Selected eclipse images sent in to APOD","hdurl":"https://apod.nasa.gov/apod/image/2310/AnnularProposal_Zhang_3500.jpg","media_type":"image","service_version":"v1","title":"Eclipse
        Rings","url":"https://apod.nasa.gov/apod/image/2310/AnnularProposal_Zhang_960.jpg"}

        '
  recorded_at: Mon, 16 Oct 2023 11:58:08 GMT
recorded_with: VCR 6.2.0
```

</details>

</details>

Ruby 3.0.4, 3.2.2(maybe all versions)
Gem 6.2.0
HTTP faraday 2.6.0
Mock webmock 3.19.1
Rails 6.1.7.3
Rspec rspec-rails 6.0.3

Best regards.

**Comment by olleolleolle** [comment]
@hirokishirai If the change in expression stops a warning, use that change.

If some RuboCop rule complains, disable that rule in code, with a `# rubocop:disable SomeCategory/ThatRule` code comment.

**Comment by hirokishirai** [comment]
@olleolleolle Thank you for your prompt response.

I posted this issue because the warning was triggered by the method at https://github.com/vcr/vcr/blob/v6.2.0/lib/vcr/configuration.rb#L378.
I will change from using VCR.use_cassette(request.uri, &request) to VCR.use_cassette(request.uri) { request.proceed }.

If this issue is no longer necessary, please feel free to close it.

Thank you once again.

**Comment by mattbrictson** [comment]
I believe this is something that needs to be fixed in vcr. I ran into a similar error recently in another project: https://github.com/capistrano/capistrano/pull/2141

In Ruby 3.3, this deprecation warning will be replaced by an actual `ArgumentError`. So vcr will break on Ruby 3.3. I confirmed this by running vcr's own specs on the `ruby:3.3-rc` docker image.

```
# ruby -v
ruby 3.3.0preview2 (2023-09-14 master e50fcca9a7) [x86_64-linux]
# bundle exec rspec spec/lib/vcr/structs_spec.rb
```

```
Failures:

  1) VCR::Request VCR::Request::FiberAware can be cast to a proc
     Failure/Error: lambda { proceed }
     
     ArgumentError:
       the lambda method requires a literal block
     # ./lib/vcr/structs.rb:307:in `to_proc'
     # ./spec/lib/vcr/structs_spec.rb:584:in `block (3 levels) in <module:VCR>'
```

I believe the fix is to replace `lambda` with `proc` on this line: https://github.com/vcr/vcr/blob/a15914e6580b5131e58afdb71f59897bed994225/lib/vcr/structs.rb#L307

This makes `structs_spec.rb` pass on Ruby 3.3.0.preview2.
